# Práctica Analisis Texto lo que sea

Explicar aquí

In [2]:
#Imports:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats

%matplotlib inline

## Paso 1: Extraer todos los datos 

Aquí básicamente vamos a tener que extraer todos los datos y meterlos en un dataset. Podemos usar pandas para eso. Además tendremos que limpiar los datos y 'organizarlos'. Podemos hacer una lista de listas (es decir, una lista con todos los jugadores/sesiones y cada uno de ellos con una lista de todos sus eventos relaccionados. si nos aseguramos que cada documento es TODA la lista de eventos del jugador, este paso será bastante fácil.)

In [4]:
jug = [[1, 2, 3], [4, 2], [3]]

## Paso 2: Calcular las métricas individuales

Como muchas de las metricas no se calculan con la raw data de todos los jugadores, tendremos que extraer primero los datos necesarios.

In [6]:
#%%writefile filespy/necesaryData.py

# Creacion de las columnas que vamos a usar
col_names =  ['ID','MuertesTutorial', 'MuertesN1', 'MuertesN2', 'MuertesN3']

# create an empty dataframe
# with columns
singleDf  = pd.DataFrame(columns = col_names)

# show the dataframe
singleDf

Empty DataFrame
Columns: [ID, MuertesTutorial, MuertesN1, MuertesN2, MuertesN3]
Index: []

In [7]:
#%%writefile filespy/Muertes.py
#TODO ESTO SON PRUEBAS DE AURORA PARA ENSEÑAR COMO APENDEAR
#BORRAR UNA VEZ NOS PONGAMOS CON LOS DATOS DE VERDAD 

#Importacion para evento random
from numpy.random import randint
#Ejemplo qye encontré de una manera de añadir al dataframe
for i in range(5):
     singleDf.loc[i] = ['name' + str(i)] + list(randint(10, size=4))

#Probablemente tengamos que hacerlo así: 
#Usamos una lista/array para guardar toda la informacion
#Y luego volcamos al dataframe
prubaData = ['name7', 0, 0, 0, 0]
singleDf.loc[6] = prubaData;

singleDf

      ID  MuertesTutorial  MuertesN1  MuertesN2  MuertesN3
0  name0                9          8          7          4
1  name1                7          6          5          8
2  name2                1          8          6          7
3  name3                7          5          4          1
4  name4                5          6          8          4
6  name7                0          0          0          0

In [8]:
#%%writefile filespy/jugadores.py
#En esta celda es donde haremos el for por cada jugador (sessionID) distinto.
#Si lo hacemos bien podemos usar las librerias para ahorrarnos el trabajo.

#Valor de jugadores arbitrario
for i in range(len(jug)):
    dataJug = ['name7', 0, 0, 0, 0]

    print(jug[i])
    #Loopear todos los eventos, y tener un switch para que segun event-type haga una cosa u otra.
    #BUCLE
    for j in range(len(jug[i])):
        #SWITCH
        j
        match i:
            case "":
                break
            case "1":
                break
            case _:
                break
        algomas
    
    #Posteriormente anexionamos jugoslavia (es broma solo anexionamos a tu madre)
    singleDf.loc[i] = dataJug;

[1, 2, 3]
[4, 2]
[3]

Aqui explicamos lo que hemos hecho.

## Paso 3: Calcular las métricas globales y Analisis

Aquí simplemente cogeríamos el dataset de los jugadores y, usando numpy y graficos super guapos de scipy y seaborn enseñar y analizarlos

In [11]:
print("ayuda")

ayuda

## Paso 4: Conclusiones

Esta parte es yapeo puro